### department 등록
POST http://localhost:8080/departments
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "id":"CS0001",
  "name":"고객서비스1팀"
}

### department 조회
GET http://localhost:8080/departments/CS0001
X-USER-ID:nhnacademy

### department 수정
PUT http://localhost:8080/departments/CS0001
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "name" : "CS1팀"
}

### department 삭제
DELETE http://localhost:8080/departments/CS0001
X-USER-ID:nhnacademy


### L1001 부서조회
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:nhnacademy

### L1001, L1002 부서조회
GET http://localhost:8080/department-members?departmentIds=L1001,L1002
Accept:application/json
X-USER-ID:nhnacademy

### Exception - Missing Parameter
GET http://localhost:8080/department-members
Accept:application/json
X-USER-ID:nhnacademy

### Exception - Empty Parameter
GET http://localhost:8080/department-members?departmentIds=
Accept:application/json
X-USER-ID:nhnacademy

### Exception - application/csv
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/csv
X-USER-ID:nhnacademy

### Exception - X-USER-ID:marco
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:marco

### Exception - X-USER-ID : Empty
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:

### Exception - X-USER-ID : NULL
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json

### Content negotiation
GET http://localhost:8080/departments/L1001
Accept:application/xml
X-USER-ID:nhnacademy